<?php
/**
 * Navbar menu links for admin
 * ******************************************************
 *
 * @author Paul Brighton <escape@null.net>
 * @link http://www.phpiphany.com/
 * @copyright Copyright &copy; 2012-2013 _MD_ ProductionS
 * @license http://www.phpiphany.com/license/
 * @package views/navbar
 * @since 1.0
 *
 */



$_SESSION['pip_navbar_menu'] = (isset($_SESSION['pip_navbar_menu']) and $_SESSION['pip_navbar_menu'])? $_SESSION['pip_navbar_menu'] :
		array(
			array(
				'url' => $dir . 'admin',
				'name' => 'Main',
				'active' => true
			),
			array(
				'type' => 'dropdown',
				'name' => 'Administration',
				'active' => false,
				'submenu' => array(
					array(
						'url' => $dir . 'scaffolding',
						'name' => 'Scaffolding',
						'active' => false
					),
					array(
						'url' => $dir . 'admin/plugins',
						'name' => 'Plugins',
						'active' => false
					),
					array(
						'url' => $dir . 'admin/migration',
						'name' => 'Migration',
						'active' => false
					),
					array(
						'url' => $dir . 'admin/maintenance',
						'name' => 'Maintenance',
						'title' => 'Put the system in maintenance mode',
						'active' => false
					),
					array(
						'url' => $dir . 'download/manage',
						'name' => 'Download Manager',
						'title' => 'View/Delete all files stored generated by or uploaded into the system',
						'active' => false
					),
				)
			),
			array(
				'type' => 'dropdown',
				'name' => 'Actions',
				'active' => false,
				'submenu' => array(
					array(
						'url' => $dir . 'users',
						'name' => 'Users',
						'title' => 'Manage system users',
						'active' => false
					),
					array(
						'url' => $dir . 'groups',
						'name' => 'Groups',
						'title' => 'Manage system groups',
						'active' => false
					),
					array(
						'url' => $dir . 'admin/export',
						'name' => 'Export',
						'title' => 'Export system data',
						'active' => false
					),
					array(
						'url' => $dir . 'admin/import',
						'name' => 'Import',
						'title' => 'Import data into the system',
						'active' => false
					),
				)
			),
		);

